### PR TITLE
Tidy up the version script

### PR DESCRIPTION
**Pull request by andrewnicols**

### CODE REVIEW

**Comment by FMCorz** [comment]
Thanks Andrew. Can you described the added value of your changes?

**Comment by FMCorz** [comment]
I (finally) noticed the use of a constant over hardcoded string and thought it was valuable. Thanks!

**Comment by FMCorz** [comment]
Noticed too late, but it might be better to stick with the `set_config` rather than the call `$DB`. Thoughts?

**Comment by andrewnicols** [comment]
Ah - good thought. I can't recall why I did that so probably better to switch back.
Sorry I missed your comment 2 years ago!

**Pull request merged**
