### PR TITLE
Replace references of `master` with `main`

### PR DESCRIPTION
**Pull request by junpataleta**
Additional notes:
- `DoctorCommand.masterbranch` has been renamed to `DoctorCommand.mainbranch` but the `--masterbranch` argument is retained (for now).

See https://tracker.moodle.org/browse/MDLSITE-7418 for more information.

### CODE REVIEW

**Comment by HuongNV13** [comment]
Thanks for working on this, Jun. The patch looks correct to me.
I have tested the patch, including #222 and it worked for me. (Only for integration.git at the moment)

**Comment by FMCorz** [comment]
Thanks for the patch Jun. I think it's pretty good, although I feel that there may be some getting used for developers that aren't necessarily aware of the internal process at HQ. For instance, if someone upgrades MDK without the knowledge that `mdk doctor` must be run, they will be left with an MDK that is fairly broken, expecting the `main` branch in several instances and lead to variety of bugs.

Generally speaking, I try to keep upgrades as smooth as possible else users fear upgrading altogether. It would be fair for users to be fairly bothered if upgrading MDK rendered their development station somewhat unpredictable. For instance, the `tools.stableBranch` should ideally not return `main` until it has been confirmed that local instances have been updated to have a `main` branch. Now, this may be easier said than done, but that's my feeling.

This goes hand in hand with custom config values that are rendered ineffective because they have been renamed. We can't reasonably expect a user to know that these values don't apply anymore, and we don't have a good mechanism to advise that `mdk doctor` should be run (if that fixed the issue).

Lastly, I do not think anything should have a destructive behaviour. Keeping a master branch unused is probably fair enough, especially as the master branch is not disappearing from Moodle completely yet.

Let me know if I can be of further assistance with this change.

**Comment by junpataleta** [comment]
Hi, @FMCorz! I have added an additional commit: https://github.com/FMCorz/mdk/pull/221/commits/646956918a940fd2f6cc76dd535a2df82a3c31f3.

I changed my mind about `tools.stableBranch()` and implemented the fallback mechanism there. But in order to do so, I had to pass a git object from the code calling it to enable the checking of the local remote for the presence of the main branch.

With this, the changes to `moodle.checkout_stable()` and `moodle.update()` in the fixup commit were reverted.

Here's a [diff of the changes since your last review](https://github.com/junpataleta/mdk/compare/mastertomain%7E2...junpataleta:mdk:mastertomain) to make it easier for you to view the changes. 

Once everything's okay, I'll squash the commits into one (or at least organise them better).

Cheers!

**Comment by junpataleta** [comment]
I've come up with a simpler version of the patch that provides support for the `main` branch and sets it as default but provides a fallback to the `master` branch. There are also no config changes in the patch so devs won't have to do anything after upgrading.

We can go with the rest of the renaming on a separate issue.

Feel free to check it out!
https://github.com/FMCorz/mdk/compare/master...junpataleta:mdk:tomain_min

I'm happy to amend the current patch for this pull request with this minimal change should we decide that this is better.

Cheers!

**Comment by FMCorz** [comment]
Thanks Jun! The minimal patch looks great. I'd only recommend that we still allow `--version master` in the various commands that take this argument. Kudos for offering to re-use a previously created _MDL-XXX-master_ in `mdk fix`.

**Comment by junpataleta** [comment]
Thanks, Fred!

I added kept `master` and added `main` in `tools.version_options` to keep supporting this version.

I also added another commit to support rebasing on master instances and branches.

**Comment by FMCorz** [comment]
Thanks a lot Jun!

**Pull request merged**
